travis:
  secure:
    BINSTAR_TOKEN: mie6jFoKNjNG5f2y8CVDe0M5+drYqCipahYZO37pdeMsRqK/xB+9vpSQV57tL08M/xFwLsY85T2uSBj9HRIpS6Kb7odkYzzKqQGVos9AYMEPcjoOtCRdR/Jy5XAiYm2cGSzZvhd9AJqyb+hBMupn736QVENFirpN3JhUnXcX1++ScHKNlX7ZoiQlVBQUtlFpWfCW5ySQfPVTXTnHkVHD56i3H/HjZGv5goCdbidJjnx/wCHc+UeNtPw2Jeq80TqfknLYFWKg0+S8yM9ergCNa1hdc4uWNsHyBLWWWah5HuktWT3kt9I97wH5Qc/9tjnxFF6i5jPTm5cg8H4n7+DqhtiFVDnlTuAA4UYeKh3WcAwFgGd4J02ex3JdQUF4YGUHipFvTRbp8kI11WCITnUMHJwcN0C91yzlHRjXqELgVnm7vhGp7hpiy09mp1gvP8Z6YbU18RCVCTAkp4f+l2DyhTU52tLzUj+0nIH8uCRFLxkhR3juC/kLMR9QdJyvoQpccTGU643PGyAkMIE8XqXMez+XhclsohMJ0TLzXruuDXHhFC7YpQIh8j4SmPW3hbdwZeCEgXYinJf1KLPLDiprkBAJZ+6+NDk2qu7HIBmBapki1Fc2XDhyVwybdibe6bQufNGqTUE9oyLCimrgDEDuc8ei3urJBAAm99SYmpVAu98=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
