travis:
  secure:
    BINSTAR_TOKEN: efHuMTep9Ru6jZD2yxX3lFHjLN1Lw93NRRCkIXeQR3PqGWTkqk+AkeTAlGS9Q3C4fS69ZJNSuq0EwK7/lMRlg8/TGUSHb4t0mILqV0ycSagIzCyRohvScGa8H5fZl1KWiV2i1NRLUvQlDy/j0+GbMzCOSbnS+Jccn52kEnDKLq4xiVKUR7dl5qBqNEticKSLG9GxejV4sdT+nxHaR6a9hWC2agZ+sCaj7v/lCWw56j3A1ZVSeYK3GFI9qeEa4WIApkP/Lv8txOtoskE3CDpFOEcAnjrIX9n91CjRw2535UflfU1/Q+DbN/zGjVuBCa+6MicVhwTkh6i7qeoWmNKJzLQ5Q079oqHnQK9XXM4GyZqK0gwTt+4J+R7MigxL22esex5FGhwPvLGqBpzGexIA+mxBYuhCktOLzUlIUyDfi6XFxUKylfMW1CIC6p3ogHcOXTjGkue3jmq2/FRBfi0QjjmBj1+RRD444eA7GXwyOaY7ToUX8cgPiU86vXh/VYHSvl7iBpCeHaSqKMbBKN4UW4701HqlaUexfaZz+MGK0qEDY/KxTdj1A1N6lfENTywnuWAzI7MCVMQAetD3j1x0wTfpqfHkUvIb5felYeD/F1oMiB6qvKq97nixl6lrpXQKLoZ8WbU6t/IosPc5OsdLpwjZGx0AJ1WCFrSAyuH7zmg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
